org.gradle.jvmargs=-Xmx2G --enable-native-access=ALL-UNNAMED
org.gradle.parallel=true

minecraft_version=26.2
loader_version=0.19.4
fabric_version=0.158.0+26.2
camerapture_version=1.10.15+mc26.2
alexs_mobs_version=2.1.8+26.2-fabric
codxlib_version=1.5.1+fabric-26.2
modmenu_version=20.0.1

mod_version=0.2.2
maven_group=dev.explorercraft
archives_base_name=photosafari
